FROM python:3.10-slim AS builder
WORKDIR /app
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
COPY . /app

FROM python:3.10-slim
WORKDIR /app
COPY --from=builder /app /app
EXPOSE 8000
CMD ["python", "main.py"]
