[build-system]
requires = ["setuptools>=42"]
build-backend = "setuptools.build_meta"

[tool.pytest.ini_options]
addopts = "-q"

[tool.mypy]
files = [
    "modules/evolution_engine/energy.py",
    "modules/evolution_engine/sustainability.py",
    "monGARS/core/inference_utils.py",
    "monGARS/utils/database.py",
]
exclude = '^(?!\.?/?modules/evolution_engine/energy\.py$|\.?/?modules/evolution_engine/sustainability\.py$|\.?/?monGARS/core/inference_utils\.py$|\.?/?monGARS/utils/database\.py$).+'
mypy_path = ["typings"]

