apiVersion: v1
kind: ServiceAccount
metadata:
  name: mongars-sa
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: default
  name: mongars-controller
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["apps"]
  resources: ["deployments", "replicasets"]
  verbs: ["get", "list", "watch", "patch"]
- apiGroups: [""]
  resources: ["services"]
  verbs: ["get", "list", "watch", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: mongars-controller-binding
  namespace: default
subjects:
- kind: ServiceAccount
  name: mongars-sa
  namespace: default
roleRef:
  kind: Role
  name: mongars-controller
  apiGroup: rbac.authorization.k8s.io