apiVersion: v1
kind: ServiceAccount
metadata:
  name: mongars-sa
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: default
  name: mongars-admin
rules:
- apiGroups: [""]
  resources: ["pods", "services", "deployments", "replicasets"]
  verbs: ["get", "list", "watch", "update", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: mongars-admin-binding
  namespace: default
subjects:
- kind: ServiceAccount
  name: mongars-sa
  namespace: default
roleRef:
  kind: Role
  name: mongars-admin
  apiGroup: rbac.authorization.k8s.io