name: Python with uv setup
description: Set up Python and uv with pinned GitHub Actions
inputs:
  python-version:
    description: Python version to install
    required: true
runs:
  using: composite
  steps:
    - name: Set up Python
      uses: actions/setup-python@39cd14951b08e74b54015e9e001cdefcf80e669f # v5.1.1
      with:
        python-version: ${{ inputs.python-version }}

    - name: Set up uv
      uses: astral-sh/setup-uv@3b9817b1bf26186f03ab8277bab9b827ea5cc254 # v3.2.0
