apiVersion: v1
kind: Secret
metadata:
  name: mongars-secrets
  namespace: default
type: Opaque
stringData:
  DB_PASSWORD: "securepassword"
  SECRET_KEY: "complex-secret-key"
  NEO4J_PASSWORD: "StrongPassword123!"