from __future__ import annotations

from typing import Any, Callable

class _DeploymentHandle:
    def options(self, *args: Any, **kwargs: Any) -> _DeploymentHandle: ...
    def remote(self, *args: Any, **kwargs: Any) -> Any: ...

class _ServeModule:
    def deployment(
        self, *args: Any, **kwargs: Any
    ) -> Callable[[Any], _DeploymentHandle]: ...
    def run(self, deployment: Any, *args: Any, **kwargs: Any) -> Any: ...
    def get_deployment(self, name: str) -> Any: ...

serve: _ServeModule

def init(*args: Any, **kwargs: Any) -> Any: ...
def is_initialized() -> bool: ...

__all__ = ["serve", "init", "is_initialized"]
